import { CodeLabStorage, makeProject } from './codelab-storage.js';

const $ = (id) => document.getElementById(id);
const esc = (value = '') => String(value).replace(/[&<>"']/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));
const uid = (prefix = 'item') => `${prefix}-${Date.now()}-${Math.random().toString(36).slice(2, 7)}`;
const templates = [
  { id: 'landing', name: 'Landing Page', description: 'Uma página de apresentação responsiva.', tech: 'HTML · CSS · JS', files: { 'index.html': '<main class="hero"><span class="eyebrow">NOVA IDEIA</span><h1>Constrói algo memorável.</h1><p>Uma landing page começa com uma boa pergunta.</p><a href="#start">Começar agora →</a></main><script src="script.js"><\/script>', 'style.css': ':root{font-family:system-ui;color:#16202a;background:#eef4ff}body{margin:0}.hero{max-width:720px;margin:15vh auto;padding:40px}.eyebrow{color:#356dff;font-weight:700}h1{font-size:clamp(42px,8vw,86px);margin:14px 0}a{color:#356dff}', 'script.js': 'console.log("Landing page pronta");' } },
  { id: 'todo', name: 'To-do list', description: 'Lista de tarefas com eventos e estado local.', tech: 'HTML · CSS · JS', files: { 'index.html': '<h1>As minhas tarefas</h1><form id="form"><input id="task" placeholder="Nova tarefa"><button>Adicionar</button></form><ul id="list"></ul><script src="script.js"><\/script>', 'style.css': 'body{max-width:600px;margin:10vh auto;font:16px system-ui;padding:20px}li{margin:10px 0}button{cursor:pointer}', 'script.js': 'const form=document.querySelector("#form"); const list=document.querySelector("#list"); form.addEventListener("submit",(event)=>{event.preventDefault(); const value=document.querySelector("#task").value.trim(); if(!value)return; const item=document.createElement("li"); item.textContent=value; list.append(item); form.reset(); console.log("Tarefa adicionada",value);});' } },
  { id: 'dashboard', name: 'Dashboard', description: 'Cartões de métricas para explorar layouts.', tech: 'HTML · CSS', files: { 'index.html': '<main><h1>Visão geral</h1><section class="grid"><article><small>VISITAS</small><strong>12.480</strong><span>+18,4%</span></article><article><small>PROJETOS</small><strong>248</strong><span>+8,1%</span></article><article><small>CONVERSÃO</small><strong>4,8%</strong><span>+2,2%</span></article></section></main>', 'style.css': '*{box-sizing:border-box}body{margin:0;background:#111827;color:#f8fafc;font:16px system-ui}main{max-width:900px;margin:12vh auto;padding:24px}.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:16px}article{padding:24px;border:1px solid #334155;border-radius:16px;background:#1e293b}small,span{display:block;color:#94a3b8}strong{display:block;font-size:40px;margin:16px 0}@media(max-width:600px){.grid{grid-template-columns:1fr}}' } },
  { id: 'game', name: 'Jogo simples', description: 'Um botão, um contador e espaço para experimentar.', tech: 'HTML · CSS · JS', files: { 'index.html': '<h1>Contador de pontos</h1><p id="score">0</p><button id="add">Ganhar ponto</button><script src="script.js"><\/script>', 'style.css': 'body{text-align:center;margin:15vh auto;font:20px system-ui}#score{font-size:80px;color:#39e58c}button{padding:14px 22px;border:0;border-radius:10px;background:#39e58c;cursor:pointer}', 'script.js': 'let score=0; document.querySelector("#add").onclick=()=>{score+=1;document.querySelector("#score").textContent=score;console.log("Pontuação",score)};' } }
];

let project = null;
let projects = [];
let activeFile = '';
let autoSaveTimer = 0;
let editorMode = 'textarea';
let monacoEditor = null;
let currentTab = 'editor';

function toast(message, kind = '') { const node = $('ide-toast'); if (!node) return; node.textContent = message; node.className = `ide-toast is-visible ${kind}`; clearTimeout(toast.timer); toast.timer = setTimeout(() => node.classList.remove('is-visible'), 2800); }
function getFileContent() { return project?.files?.[activeFile] || ''; }
function setFileContent(value) { if (!project || !activeFile) return; project.files[activeFile] = value; project.updatedAt = new Date().toISOString(); }
function updateSaveStatus(text = 'Guardado localmente') { const node = $('ide-save-status'); if (node) node.textContent = text; }
async function saveProject(show = false) { if (!project) return; updateSaveStatus('A guardar…'); await CodeLabStorage.saveProject(project); await saveHistory(); updateSaveStatus('Guardado localmente'); if (show) toast('Projeto guardado neste navegador.', 'success'); }
async function saveHistory() { if (!project) return; const history = await CodeLabStorage.getMeta('history', []); const snapshot = { id: uid('snapshot'), projectId: project.id, projectName: project.name, createdAt: new Date().toISOString(), files: structuredClone(project.files) }; const next = [...history.filter((item) => item.projectId !== project.id), snapshot].slice(-50); await CodeLabStorage.saveMeta('history', next); renderHistory(next); }
function renderHistory(history = []) { const node = $('ide-history-list'); if (!node) return; const items = history.filter((item) => item.projectId === project?.id).slice(-8).reverse(); node.innerHTML = items.length ? items.map((item) => `<button class="ide-history-item" data-history="${item.id}"><span>${new Date(item.createdAt).toLocaleString('pt-PT', { dateStyle: 'short', timeStyle: 'short' })}</span><b>Restaurar</b></button>`).join('') : '<span>Ainda sem versões guardadas.</span>'; }
async function restoreHistory(id) { const history = await CodeLabStorage.getMeta('history', []); const snapshot = history.find((item) => item.id === id); if (!snapshot || !project || !confirm('Restaurar esta versão local? As alterações atuais serão substituídas.')) return; project.files = structuredClone(snapshot.files); activeFile = Object.keys(project.files)[0]; renderFileTree(); syncEditorFromState(); updateLanguage(); await saveProject(true); }
function scheduleSave() { clearTimeout(autoSaveTimer); updateSaveStatus('Alterações por guardar…'); autoSaveTimer = setTimeout(() => saveProject(), 700); }

function renderFileTree() {
  const tree = $('ide-file-tree'); if (!tree || !project) return;
  const files = Object.keys(project.files).sort((a, b) => a.localeCompare(b));
  tree.innerHTML = files.map((file) => `<button class="ide-file ${file === activeFile ? 'is-active' : ''}" data-file="${esc(file)}"><span>${file.endsWith('.html') ? '◈' : file.endsWith('.css') ? '◌' : file.endsWith('.js') ? 'ƒ' : '◇'}</span>${esc(file)}</button>`).join('');
}
function renderProjects() {
  const list = $('ide-project-list'); if (!list) return;
  list.innerHTML = projects.length ? projects.map((item) => `<button class="ide-project ${item.id === project?.id ? 'is-active' : ''}" data-project="${item.id}"><span><strong>${esc(item.name)}</strong><small>${Object.keys(item.files || {}).length} ficheiros · ${new Date(item.updatedAt).toLocaleDateString('pt-PT')}</small></span><b>↗</b></button>`).join('') : '<p class="ide-empty">Ainda não tens projetos. Cria o primeiro.</p>';
}
function syncEditorFromState() { if (editorMode === 'monaco' && monacoEditor) monacoEditor.setValue(getFileContent()); else if ($('ide-editor')) $('ide-editor').value = getFileContent(); }
function syncStateFromEditor() { if (editorMode === 'monaco' && monacoEditor) setFileContent(monacoEditor.getValue()); else if ($('ide-editor')) setFileContent($('ide-editor').value); }
function selectFile(file) { if (!project?.files[file]) return; syncStateFromEditor(); activeFile = file; project.activeFile = file; $('ide-file-name').textContent = file; $('ide-project-name').textContent = project.name.toUpperCase(); syncEditorFromState(); renderFileTree(); updateLanguage(); updatePreviewIfNeeded(); }
function updateLanguage() { const ext = activeFile.split('.').pop(); const language = ext === 'html' ? 'HTML' : ext === 'css' ? 'CSS' : ext === 'js' ? 'JavaScript' : ext === 'json' ? 'JSON' : ext === 'md' ? 'Markdown' : 'Texto'; $('ide-language').textContent = language; }

function buildSrcDoc() {
  const html = project?.files?.['index.html'] || '';
  const css = project?.files?.['style.css'] || '';
  const js = project?.files?.['script.js'] || '';
  const bridge = `<script>(function(){const send=(type,args)=>parent.postMessage({source:'world69-codelab-preview',type,args:Array.from(args).map(v=>{try{return typeof v==='object'?JSON.stringify(v):String(v)}catch(_){return String(v)}})},'*');['log','warn','error'].forEach(k=>{const original=console[k];console[k]=function(){send(k,arguments);original.apply(console,arguments)}});window.addEventListener('error',e=>send('error',[e.message+' (linha '+e.lineno+')']));})();<\/script>`;
  const safeJs = js.replace(/<\/script/gi, '<\\/script');
  const documentHtml = html.replace(/<link[^>]+href=["']style\.css["'][^>]*>/i, `<style>${css.replace(/<\/style/gi, '<\\/style')}</style>`).replace(/<script[^>]+src=["']script\.js["'][^>]*><\/script>/i, `<script>${safeJs}<\/script>`);
  return /<head/i.test(documentHtml) ? documentHtml.replace(/<head>/i, `<head><meta name="viewport" content="width=device-width,initial-scale=1">${bridge}`) : `${bridge}${documentHtml}`;
}
function clearConsole() { const node = $('ide-console-output'); if (node) node.innerHTML = '<div class="ide-console-empty">A saída do teu programa aparece aqui.</div>'; }
function appendConsole(type, args) { const node = $('ide-console-output'); if (!node) return; node.querySelector('.ide-console-empty')?.remove(); const line = document.createElement('div'); line.className = `console-line ${type}`; line.innerHTML = `<span class="console-kind">${type === 'error' ? 'ERR' : type.toUpperCase()}</span><span>${esc(args.join(' '))}</span>`; node.appendChild(line); node.scrollTop = node.scrollHeight; }
async function runApiRequest() { const url = $('api-url').value.trim(); if (!/^https?:\/\//i.test(url)) return toast('Indica uma URL HTTP/HTTPS válida.', 'error'); const button = $('api-send'); const result = $('api-result'); const method = $('api-method').value; const body = $('api-body').value.trim(); button.disabled = true; button.textContent = 'A enviar…'; const started = performance.now(); try { const response = await fetch(url, { method, headers: body ? { 'Content-Type': 'application/json' } : {}, body: body && method !== 'GET' && method !== 'DELETE' ? body : undefined }); const text = await response.text(); let formatted = text; try { formatted = JSON.stringify(JSON.parse(text), null, 2); } catch (_) {} result.textContent = `HTTP ${response.status} ${response.statusText} · ${Math.round(performance.now() - started)} ms\n\n${formatted.slice(0, 12000)}`; result.className = response.ok ? 'api-ok' : 'api-error'; } catch (error) { result.textContent = `Erro de rede/CORS: ${error.message}\n\nO CodeLab não contorna CORS nem autenticação.`; result.className = 'api-error'; } finally { button.disabled = false; button.textContent = 'Enviar'; } }
async function openTemplate(id) { const template = templates.find((item) => item.id === id); if (template) await createProject(template.name, structuredClone(template.files)); }
function runPreview() { syncStateFromEditor(); clearConsole(); const frame = $('ide-preview-frame'); frame.srcdoc = buildSrcDoc(); frame.classList.add('is-running'); $('ide-run').disabled = true; $('ide-run').textContent = 'A executar…'; setTimeout(() => { $('ide-run').disabled = false; $('ide-run').textContent = '▶ Executar'; frame.classList.remove('is-running'); }, 500); saveProject(); }
function stopPreview() { const frame = $('ide-preview-frame'); frame.srcdoc = '<div style="font:14px system-ui;padding:30px;color:#81909a">Preview parado. Carrega em Executar para começar.</div>'; $('ide-run').disabled = false; $('ide-run').textContent = '▶ Executar'; }
function updatePreviewIfNeeded() { if (currentTab === 'preview') runPreview(); }

async function createProject(name = 'Projeto sem título', files = null) { project = makeProject(name, files); projects = [project, ...projects]; activeFile = project.activeFile; await CodeLabStorage.saveProject(project); renderProjects(); renderFileTree(); syncEditorFromState(); updateLanguage(); $('ide-project-name').textContent = project.name.toUpperCase(); $('ide-file-name').textContent = activeFile; showIDE(); toast('Projeto criado localmente.', 'success'); }
async function loadProject(id) { const found = projects.find((item) => item.id === id) || await CodeLabStorage.getProject(id); if (!found) return; project = found; projects = [project, ...projects.filter((item) => item.id !== project.id)]; activeFile = project.activeFile || Object.keys(project.files)[0]; renderProjects(); renderFileTree(); syncEditorFromState(); updateLanguage(); $('ide-project-name').textContent = project.name.toUpperCase(); $('ide-file-name').textContent = activeFile; showIDE(); toast(`${project.name} aberto.`, 'success'); }
async function duplicateProject() { if (!project) return; await createProject(`${project.name} cópia`, structuredClone(project.files)); }
async function deleteProject() { if (!project || !confirm(`Excluir “${project.name}” apenas deste navegador?`)) return; await CodeLabStorage.deleteProject(project.id); projects = projects.filter((item) => item.id !== project.id); project = projects[0] || null; if (project) { activeFile = project.activeFile || Object.keys(project.files)[0]; } renderProjects(); renderFileTree(); syncEditorFromState(); updateLanguage(); toast('Projeto excluído.', 'success'); }

function openNewFile() { const name = prompt('Nome do ficheiro (ex.: components.js):'); if (!name || !/^[\w./-]+$/.test(name) || project.files[name]) return toast('Nome inválido ou ficheiro já existente.', 'error'); project.files[name] = ''; selectFile(name); scheduleSave(); }
function renameFile() { if (!project || !activeFile) return; const name = prompt('Novo nome do ficheiro:', activeFile); if (!name || name === activeFile || !/^[\w./-]+$/.test(name) || project.files[name]) return; project.files[name] = project.files[activeFile]; delete project.files[activeFile]; activeFile = name; renderFileTree(); syncEditorFromState(); updateLanguage(); scheduleSave(); }
function deleteFile() { if (!project || !activeFile || Object.keys(project.files).length <= 1) return toast('Um projeto precisa de pelo menos um ficheiro.', 'error'); if (!confirm(`Excluir ${activeFile}?`)) return; delete project.files[activeFile]; activeFile = Object.keys(project.files)[0]; renderFileTree(); syncEditorFromState(); updateLanguage(); scheduleSave(); }

async function exportProject() { if (!project) return; syncStateFromEditor(); const files = project.files; try { const module = await import('https://cdn.jsdelivr.net/npm/jszip@3.10.1/+esm'); const zip = new module.default(); Object.entries(files).forEach(([name, content]) => zip.file(name, content)); const blob = await zip.generateAsync({ type: 'blob' }); download(blob, `${project.name.replace(/[^\w-]+/g, '-').toLowerCase() || 'project'}.zip`); toast('ZIP exportado.', 'success'); } catch (_) { const content = Object.entries(files).map(([name, value]) => `/* ===== ${name} ===== */\n${value}`).join('\n\n'); download(new Blob([content], { type: 'text/plain' }), `${project.name}.txt`); toast('JSZip ficou offline; exportei uma cópia de texto.', 'error'); } }
function download(blob, name) { const link = document.createElement('a'); link.href = URL.createObjectURL(blob); link.download = name; link.click(); setTimeout(() => URL.revokeObjectURL(link.href), 1000); }
async function importFiles(fileList) { const selected = Array.from(fileList || []).slice(0, 30); if (!selected.length) return; const first = selected[0]; if (/\.zip$/i.test(first.name) || first.type === 'application/zip') { try { const module = await import('https://cdn.jsdelivr.net/npm/jszip@3.10.1/+esm'); const zip = await module.default.loadAsync(await first.arrayBuffer()); const files = {}; for (const [name, entry] of Object.entries(zip.files)) { if (entry.dir || name.split('/').length > 3) continue; const clean = name.split('/').filter(Boolean).slice(-2).join('/'); if (clean && clean.length < 160) files[clean] = await entry.async('string'); } if (!Object.keys(files).length) throw new Error('ZIP vazio'); if (!files['index.html']) files['index.html'] = '<main><h1>Projeto importado</h1></main>'; return createProject('Projeto ZIP importado', files); } catch (_) { return toast('Não foi possível ler este ZIP. Confere se contém ficheiros de texto.', 'error'); } } const files = {}; for (const file of selected) { if (file.size > 1024 * 1024 || /\.zip$/i.test(file.name)) continue; files[file.webkitRelativePath?.split('/').slice(1).join('/') || file.name] = await file.text(); } if (!Object.keys(files).length) return toast('Nenhum ficheiro de texto válido encontrado.', 'error'); if (!files['index.html']) files['index.html'] = '<main><h1>Novo projeto importado</h1></main>'; await createProject('Projeto importado', files); }
async function exportData() { const data = await CodeLabStorage.exportData(); download(new Blob([JSON.stringify(data, null, 2)], { type: 'application/json' }), 'world69-codelab-dados.json'); toast('Dados exportados sem senhas ou segredos.', 'success'); }
async function importData(file) { try { const data = JSON.parse(await file.text()); await CodeLabStorage.importData(data); projects = await CodeLabStorage.listProjects(); project = projects[0] || null; if (project) { activeFile = project.activeFile || Object.keys(project.files)[0]; renderProjects(); renderFileTree(); syncEditorFromState(); updateLanguage(); showIDE(); } toast('Dados importados.', 'success'); } catch (_) { toast('Não foi possível importar este ficheiro JSON.', 'error'); } }

function showIDE() { $('ide-section').hidden = false; $('ide-section').scrollIntoView({ behavior: 'smooth', block: 'start' }); }
function setTab(tab) { currentTab = tab; document.querySelectorAll('[data-ide-tab]').forEach((button) => button.classList.toggle('is-active', button.dataset.ideTab === tab)); document.querySelectorAll('.ide-panel').forEach((panel) => panel.hidden = panel.dataset.idePanel !== tab); if (tab === 'preview') runPreview(); }
function toggleFocus() { document.body.classList.toggle('codelab-focus-mode'); $('ide-section').classList.toggle('is-focus-mode'); toast($('ide-section').classList.contains('is-focus-mode') ? 'Modo foco ativo. Esc para sair.' : 'Modo foco desativado.'); }
function openPalette() { $('command-palette').hidden = false; $('palette-search').focus(); }
function closePalette() { $('command-palette').hidden = true; }
async function loadMonaco() { if (editorMode === 'monaco') return; const status = $('ide-editor-status'); status.textContent = 'A carregar editor avançado…'; try { await new Promise((resolve, reject) => { const script = document.createElement('script'); script.src = 'https://cdnjs.cloudflare.com/ajax/libs/monaco-editor/0.52.2/min/vs/loader.min.js'; script.onload = resolve; script.onerror = reject; document.head.appendChild(script); }); await new Promise((resolve) => { window.require.config({ paths: { vs: 'https://cdnjs.cloudflare.com/ajax/libs/monaco-editor/0.52.2/min/vs' } }); window.require(['vs/editor/editor.main'], resolve); }); const host = $('ide-monaco'); monacoEditor = window.monaco.editor.create(host, { value: getFileContent(), language: activeFile.endsWith('.css') ? 'css' : activeFile.endsWith('.js') ? 'javascript' : 'html', theme: 'vs-dark', automaticLayout: true, minimap: { enabled: true }, fontSize: 13, tabSize: 2 }); $('ide-editor').hidden = true; host.hidden = false; editorMode = 'monaco'; monacoEditor.onDidChangeModelContent(() => { setFileContent(monacoEditor.getValue()); scheduleSave(); }); status.textContent = 'Monaco ativo'; toast('Editor avançado carregado.', 'success'); } catch (_) { status.textContent = 'Editor leve ativo'; toast('Monaco não ficou disponível; o editor leve continua ativo.', 'error'); } }

function bind() {
  $('open-ide')?.addEventListener('click', async () => { if (!projects.length) await createProject(); else { project = projects[0]; activeFile = project.activeFile || Object.keys(project.files)[0]; renderProjects(); renderFileTree(); syncEditorFromState(); updateLanguage(); showIDE(); } });
  $('ide-new-project')?.addEventListener('click', () => createProject(prompt('Nome do novo projeto:', 'Meu projeto') || 'Meu projeto'));
  $('ide-duplicate')?.addEventListener('click', duplicateProject); $('ide-delete-project')?.addEventListener('click', deleteProject); $('ide-save')?.addEventListener('click', () => saveProject(true)); $('ide-export')?.addEventListener('click', exportProject); $('ide-import')?.addEventListener('click', () => $('ide-file-input').click()); $('ide-file-input')?.addEventListener('change', (event) => importFiles(event.target.files));
  $('ide-data-export')?.addEventListener('click', exportData); $('ide-data-import')?.addEventListener('change', (event) => event.target.files[0] && importData(event.target.files[0])); $('ide-clear-data')?.addEventListener('click', async () => { if (!confirm('Limpar apenas os dados locais do CodeLab?')) return; await CodeLabStorage.clear(); projects = []; project = null; renderProjects(); renderFileTree(); toast('Dados locais do CodeLab limpos.', 'success'); });
  $('ide-file-tree')?.addEventListener('click', (event) => { const button = event.target.closest('[data-file]'); if (button) { project.activeFile = button.dataset.file; selectFile(button.dataset.file); } });
  $('ide-project-list')?.addEventListener('click', (event) => { const button = event.target.closest('[data-project]'); if (button) loadProject(button.dataset.project); });
  $('ide-history-list')?.addEventListener('click', (event) => { const button = event.target.closest('[data-history]'); if (button) restoreHistory(button.dataset.history); });
  $('ide-editor')?.addEventListener('input', () => { setFileContent($('ide-editor').value); scheduleSave(); }); $('ide-editor')?.addEventListener('keydown', (event) => { if (event.key === 'Tab') { event.preventDefault(); const start = event.target.selectionStart; event.target.setRangeText('  ', start, event.target.selectionEnd, 'end'); event.target.dispatchEvent(new Event('input')); } if ((event.ctrlKey || event.metaKey) && event.key === 'Enter') runPreview(); });
  $('ide-new-file')?.addEventListener('click', openNewFile); $('ide-rename-file')?.addEventListener('click', renameFile); $('ide-delete-file')?.addEventListener('click', deleteFile); $('ide-run')?.addEventListener('click', runPreview); $('ide-stop')?.addEventListener('click', stopPreview); $('ide-reload')?.addEventListener('click', runPreview); $('ide-clear-console')?.addEventListener('click', clearConsole); $('ide-copy-code')?.addEventListener('click', async () => { await navigator.clipboard?.writeText(getFileContent()); toast('Código copiado.', 'success'); }); $('ide-monaco-load')?.addEventListener('click', loadMonaco); $('ide-focus')?.addEventListener('click', toggleFocus); $('ide-fullscreen')?.addEventListener('click', () => $('ide-section').requestFullscreen?.()); $('api-send')?.addEventListener('click', runApiRequest); document.querySelectorAll('[data-template]').forEach((button) => button.addEventListener('click', () => openTemplate(button.dataset.template)));
  document.querySelectorAll('[data-ide-tab]').forEach((button) => button.addEventListener('click', () => setTab(button.dataset.ideTab)));
  $('palette-close')?.addEventListener('click', closePalette); $('command-palette')?.addEventListener('click', (event) => { if (event.target === $('command-palette')) closePalette(); }); $('palette-search')?.addEventListener('input', (event) => { const query = event.target.value.toLowerCase(); document.querySelectorAll('.palette-command').forEach((item) => item.hidden = !item.textContent.toLowerCase().includes(query)); }); document.querySelectorAll('.palette-command').forEach((item) => item.addEventListener('click', () => { closePalette(); $(item.dataset.command)?.click(); }));
  window.addEventListener('message', (event) => { if (event.data?.source === 'world69-codelab-preview') appendConsole(event.data.type, event.data.args || []); }); window.addEventListener('keydown', (event) => { if ((event.ctrlKey || event.metaKey) && event.shiftKey && event.key.toLowerCase() === 'p') { event.preventDefault(); openPalette(); } if (event.key === 'Escape') { if (!$('command-palette').hidden) closePalette(); else if ($('ide-section').classList.contains('is-focus-mode')) toggleFocus(); } });
}

async function init() { bind(); projects = await CodeLabStorage.listProjects(); const history = await CodeLabStorage.getMeta('history', []); if (projects.length) { project = projects[0]; activeFile = project.activeFile || Object.keys(project.files)[0]; renderProjects(); renderFileTree(); syncEditorFromState(); updateLanguage(); $('ide-project-name').textContent = project.name.toUpperCase(); $('ide-file-name').textContent = activeFile; } else renderProjects(); renderHistory(history); clearConsole(); }
init().catch(() => toast('O CodeLab continua disponível, mas o armazenamento local está limitado.', 'error'));
