#!/usr/bin/env python3
"""Refresh the Mrzinho teaching memory from official public documentation.

This job stores source metadata and short, curated teaching prompts. It never
executes or imports code from the sources and never handles learner data.
"""
from __future__ import annotations

import hashlib
import json
import re
import time
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
MANIFEST = ROOT / "mrzinho-sources.json"
MEMORY = ROOT / "mrzinho-knowledge.generated.json"
MODULE = ROOT / "mrzinho-knowledge.generated.js"

TEACHING_MEMORY = {
    "javascript": {
        "focus": "Explicar valores, decisões e efeitos no navegador com exemplos pequenos.",
        "tip": "Mostra uma linha, prevê o resultado, executa e só depois altera outra coisa.",
    },
    "python": {
        "focus": "Usar a sintaxe legível do Python para decompor problemas e testar hipóteses.",
        "tip": "Nomeia os dados, faz uma transformação de cada vez e observa a saída.",
    },
    "cpp": {
        "focus": "Ler código moderno C++ com atenção à biblioteca standard e à propriedade dos recursos.",
        "tip": "Antes de otimizar, explica tipos, estado e ciclo de vida de cada valor.",
    },
    "logic": {
        "focus": "Transformar objetivos em entrada, passos, decisão, repetição e resultado observável.",
        "tip": "Divide um problema grande numa pergunta pequena que possa ser verificada.",
    },
}


def fetch(url: str) -> tuple[str, str]:
    request = urllib.request.Request(
        url,
        headers={"User-Agent": "World69-Mrzinho-Memory/1.0", "Accept": "text/html,application/xhtml+xml"},
    )
    with urllib.request.urlopen(request, timeout=30) as response:
        body = response.read(300_000).decode("utf-8", errors="replace")
        return response.geturl(), body


def clean_title(html: str, fallback: str) -> str:
    match = re.search(r"<title[^>]*>(.*?)</title>", html, re.I | re.S)
    if not match:
        return fallback
    return re.sub(r"\s+", " ", re.sub(r"<[^>]+>", "", match.group(1))).strip()[:180] or fallback


def main() -> int:
    manifest = json.loads(MANIFEST.read_text(encoding="utf-8"))
    now = time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime())
    entries = []
    failures = []
    for source in manifest["sources"]:
        try:
            resolved, html = fetch(source["url"])
            entries.append({
                **source,
                "resolvedUrl": resolved,
                "status": "ok",
                "title": clean_title(html, source["label"]),
                "contentHash": hashlib.sha256(html.encode("utf-8")).hexdigest()[:16],
                "checkedAt": now,
            })
        except Exception as exc:
            failures.append({"id": source["id"], "error": str(exc)[:180]})
            entries.append({**source, "status": "unavailable", "checkedAt": now})
    knowledge = {
        "version": 1,
        "updatedAt": now,
        "sources": entries,
        "failures": failures,
        "lessons": TEACHING_MEMORY,
        "policy": "Conteúdo curado e metadados de fontes; não é código executável nem memória de dados pessoais.",
    }
    MEMORY.write_text(json.dumps(knowledge, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    MODULE.write_text("// Generated by scripts/update_mrzinho.py.\nexport const mrzinhoKnowledge = " + json.dumps(knowledge, ensure_ascii=False, separators=(",", ":")) + ";\n", encoding="utf-8")
    print(f"MrZinho memory refreshed: {len(entries) - len(failures)}/{len(entries)} sources available at {now}")
    return 0 if not failures else 0


if __name__ == "__main__":
    raise SystemExit(main())
